"""add_new_column_to_users

Revision ID: ac40c91f1b1a
Revises: 97c5a4abb4b3
Create Date: 2026-06-15 20:23:54.734648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac40c91f1b1a'
down_revision: Union[str, Sequence[str], None] = '97c5a4abb4b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_attendance_session'), table_name='live_attendance')
    op.drop_index(op.f('idx_attendance_user'), table_name='live_attendance')
    op.create_index(op.f('ix_live_attendance_live_session_id'), 'live_attendance', ['live_session_id'], unique=False)
    op.create_index(op.f('ix_live_attendance_user_id'), 'live_attendance', ['user_id'], unique=False)
    op.create_index(op.f('ix_live_sessions_sprint_id'), 'live_sessions', ['sprint_id'], unique=False)
    op.drop_index(op.f('idx_submissions_sprint'), table_name='task_submissions')
    op.drop_index(op.f('idx_submissions_user_date'), table_name='task_submissions')
    op.create_index(op.f('ix_task_submissions_sprint_id'), 'task_submissions', ['sprint_id'], unique=False)
    op.create_index(op.f('ix_task_submissions_submission_date'), 'task_submissions', ['submission_date'], unique=False)
    op.create_index(op.f('ix_task_submissions_user_id'), 'task_submissions', ['user_id'], unique=False)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_task_submissions_user_id'), table_name='task_submissions')
    op.drop_index(op.f('ix_task_submissions_submission_date'), table_name='task_submissions')
    op.drop_index(op.f('ix_task_submissions_sprint_id'), table_name='task_submissions')
    op.create_index(op.f('idx_submissions_user_date'), 'task_submissions', ['user_id', 'submission_date'], unique=False)
    op.create_index(op.f('idx_submissions_sprint'), 'task_submissions', ['sprint_id'], unique=False)
    op.drop_index(op.f('ix_live_sessions_sprint_id'), table_name='live_sessions')
    op.drop_index(op.f('ix_live_attendance_user_id'), table_name='live_attendance')
    op.drop_index(op.f('ix_live_attendance_live_session_id'), table_name='live_attendance')
    op.create_index(op.f('idx_attendance_user'), 'live_attendance', ['user_id'], unique=False)
    op.create_index(op.f('idx_attendance_session'), 'live_attendance', ['live_session_id'], unique=False)
    # ### end Alembic commands ###
